### PR TITLE
small recommendation

### PR DESCRIPTION
**Pull request by andreGarvin**
can not always assume they will pass an array. And that the array will not be empty

### CODE REVIEW

**Comment by andreGarvin** [comment]
@ethanent

**Comment by ethanent** [comment]
Sorry, I don't understand the purpose of this PR. If it's attempting to add string support to the parsing method, it isn't doing so correctly. Passing "hi" to your method would return something like `{_: ['h', 'i']}` as the split method as you used it splits at each character.

**Comment by andreGarvin** [comment]
eh no I meant to put `.split(' ')`. @ethanent

**Comment by andreGarvin** [comment]
Also, you can you an argument parse to read CLI commands written to a file that you may want to execute. There are many reasons you want to do that.

**Comment by ethanent** [comment]
Ok, I kind of see what you're after here. Unfortunately your code won't function, even if you were to fix your usage of `split()`.

ex. for arg string `--hey hi --test "multiple words"`, `"multiple` and `words"` would be split up.

This'd be best handled by a regular expression.

**Pull request closed without merging**
